events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # Rute untuk Microservice Users
        location /users {
            proxy_pass http://service-users:5000;
            proxy_set_header Host $host;
        }

        # Rute untuk Microservice Products
        location /products {
            proxy_pass http://service-products:5000;
            proxy_set_header Host $host;
        }

        # Halaman default API Gateway
        location / {
            return 200 '{"message": "API Gateway NGINX berjalan. Coba akses endpoint /users atau /products"}';
            default_type application/json;
        }
    }
}
